version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

      # 🔗 Kết nối đến Azure SQL
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://alotra.database.windows.net:1433;database=AloTraWeb;encrypt=true;trustServerCertificate=true;"
      SPRING_DATASOURCE_USERNAME: "lamvandi"
      SPRING_DATASOURCE_PASSWORD: "Di25032005@"

      # ⚙️ Hibernate
      SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.SQLServerDialect"

    restart: unless-stopped
